nome : GitHub-Profile-3D-Contrib

on :
   schedule : # 03:00 JST == 18:00 UTC 
    - cron : " 0 18 * * * "
   workflow_dispatch :

jobs :
   build :
     run-on : ubuntu-latest 
    name : generate-github-profile-3d-contrib 
    steps :
      - usa : actions/checkout@v2 
      - usa : yoshi389111/github-profile-3d-contrib@0.6.0 
        env :
           GITHUB_TOKEN : ${{ secrets.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 }} 
          USERNAME : ${{ github.lucasdonordeste }} 
      - name : Commit & Empurre 
        a execução : | 
          git config user.name github-actions 
          git config user.email github-actions@github.com 
          git add -A . 
          git commit -m "gerado" 
          git push
